sudo: required
services:
  - docker
install: make prepare
if: branch = master
script:
  - make lint
  - make test
  - make build
  - make publish
if: branch = migration
script:
  - make lint
  - make test
  - make build
