sudo: required
services:
  - docker
install: false
jobs:
  include:
    - stage: continuous_integration
      if: branch = ci
      script:
        - make prepare
        - make lint
        - make test
        - make build
    - stage: deployment
      if: branch = master
      script:
        - make prepare
        - make lint
        - make test
        - make build
        - make publish
