sudo: required
services:
  - docker
install: false
jobs:
  include:
    - stage: continuous_integration
      if: NOT tag = /.*/
      script:
        - make prepare
        - make lint
        - make test
        - make build
    - stage: deployment
      if: tag = /.*/
      script:
        - make prepare
        - make lint
        - make test
        - make build
        - make publish
