sudo: required
services:
  - docker
install: make prepare
jobs:
  include:
    - stage: lint
      script: make lint
    - stage: test
      script: make test
    - stage: build
      script: make build
    - stage: publish
      if: type IN (push) AND branch = migration
      script: make publish